Repository carbon-design-system/carbon-platform, pull requests merged in 2022-03, with the labels that each got.

#394 fix(schemas): asset description to optional
  docs/resource-schemas.md
Labels: status: one more review 👀

#395 refactor(web-app): per-file sass use statements
  services/web-app/components/autolink-header/autolink-header.module.scss
  services/web-app/components/catalog-filters/catalog-filters.module.scss
  services/web-app/components/catalog-item/catalog-item.module.scss
  services/web-app/components/catalog-list/catalog-list.module.scss
  services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.module.scss
  services/web-app/components/catalog-pagination/catalog-pagination.module.scss
  services/web-app/components/catalog-results/catalog-results.module.scss
  services/web-app/components/catalog-search/catalog-search.module.scss
  services/web-app/components/catalog-sort/catalog-sort.module.scss
  services/web-app/components/catalog/catalog.module.scss
  services/web-app/components/dashboard/dashboard-item.module.scss
  services/web-app/components/dashboard/dashboard.module.scss
  services/web-app/components/footer/footer.module.scss
  services/web-app/components/framework-icon/framework-icon.module.scss
  services/web-app/components/hero/hero.module.scss
  services/web-app/components/link/link.module.scss
  services/web-app/components/markdown/markdown.module.scss
  services/web-app/components/page-breadcrumb/page-breadcrumb.module.scss
  services/web-app/components/page-header/page-header.module.scss
  services/web-app/components/page-not-found/page-not-found.module.scss
  services/web-app/components/status-icon/status-icon.module.scss
  services/web-app/layouts/layout/layout.module.scss
  services/web-app/next.config.js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].module.scss
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.module.scss
  services/web-app/pages/assets/index/index.module.scss
  services/web-app/pages/assets/libraries.module.scss
  services/web-app/pages/pages.module.scss
  services/web-app/styles/_base.scss
  services/web-app/styles/_mixins.scss
  services/web-app/styles/styles.scss
  services/web-app/styles/vendor/_carbon.scss
  services/web-app/styles/vendor/_overrides.scss
  services/web-app/styles/vendor/index.scss
Labels: status: help wanted 👐, status: one more review 👀

#348 non-Canonical Framework Collapsing
  services/web-app/components/catalog/catalog.js
Labels: status: one more review 👀

#392 feat: add demo links and tags to asset detail page
  services/web-app/components/dashboard/dashboard.module.scss
  services/web-app/components/external-links/external-links.js
  services/web-app/components/external-links/index.js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/utils/schema.js
Labels: status: ready to merge 🎉

#401 refactor: grid update for page without sidenav
  services/web-app/layouts/layout/layout.js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js
Labels: status: one more review 👀

#341 feat(web-app): add library and asset validation
  package-lock.json
  packages/schemas/internal/validation/asset-validation.schema.json
  packages/schemas/internal/validation/library-validation.schema.json
  services/web-app/lib/github.js
  services/web-app/package.json
  services/web-app/utils/resources.js
Labels: status: ready to merge 🎉

#421 fix(web-app): new object when getting allTags,fix catalog tag issue
  services/web-app/utils/schema.js
Labels: status: ready for review 👀

#410 fix: grid style fixes
  services/web-app/components/catalog-filters/catalog-filters.js
  services/web-app/components/catalog-filters/catalog-filters.module.scss
  services/web-app/components/catalog-item/catalog-item.js
  services/web-app/components/catalog-item/catalog-item.module.scss
  services/web-app/components/catalog-list/catalog-list.js
  services/web-app/components/catalog-list/catalog-list.module.scss
  services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.js
  services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.module.scss
  services/web-app/components/catalog-pagination/catalog-pagination.js
  services/web-app/components/catalog-pagination/catalog-pagination.module.scss
  services/web-app/components/catalog-results/catalog-results.js
  services/web-app/components/catalog-results/catalog-results.module.scss
  services/web-app/components/catalog-search/catalog-search.js
  services/web-app/components/catalog-search/catalog-search.module.scss
  services/web-app/components/catalog-sort/catalog-sort.js
  services/web-app/components/catalog-sort/catalog-sort.module.scss
  services/web-app/components/dashboard/dashboard-item.module.scss
  services/web-app/components/dashboard/dashboard.js
  services/web-app/components/dashboard/dashboard.module.scss
  services/web-app/components/footer/footer.module.scss
  services/web-app/components/hero/hero.module.scss
  services/web-app/components/page-header/page-header.module.scss
  services/web-app/components/page-not-found/page-not-found.module.scss
  services/web-app/layouts/layout/layout.js
  services/web-app/layouts/layout/layout.module.scss
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/assets/index/index.module.scss
  services/web-app/pages/assets/libraries.js
  services/web-app/pages/assets/libraries.module.scss
  services/web-app/pages/pages.module.scss
  services/web-app/pages/standards.js
Labels: status: ready for review 👀

#420 fix(web-app): custom status order on asset catalog
  services/web-app/components/catalog-sort/catalog-sort.js
  services/web-app/components/catalog/catalog.js
  services/web-app/data/sort.js
  services/web-app/utils/schema.js
Labels: status: ready to merge 🎉

#422 fix(web-app): address array.map console errors
  services/web-app/components/footer/footer.js
  services/web-app/layouts/layout/layout.js
Labels: status: one more review 👀

#260 fix(web-app): query refactor
  package-lock.json
  services/web-app/components/catalog-sort/catalog-sort.js
  services/web-app/components/catalog/catalog.js
  services/web-app/data/view.js
  services/web-app/package.json
  services/web-app/utils/string.js
  services/web-app/utils/use-previous.js
  services/web-app/utils/use-query-state.js
Labels: status: one more review 👀

#390 wip(web-app): log message api and call from middleware
  docs/services-web-app.md
  services/web-app/config/constants.js
  services/web-app/middleware/requireSession.js
  services/web-app/pages/_middleware.js
  services/web-app/pages/api/log-request.js
  services/web-app/utils/retrieveUser.js
  services/web-app/utils/sendLocalRequest.js
Labels: status: ready for review 👀

#396 feat: tabs component
  services/web-app/components/page-tabs/index.js
  services/web-app/components/page-tabs/page-tabs.js
  services/web-app/components/page-tabs/page-tabs.module.scss
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].js
Labels: status: ready to merge 🎉

#427 feat(web-app): add INDEX_ALL local env variable
  docs/services-web-app.md
  services/web-app/.env.example
  services/web-app/lib/github.js
Labels: status: ready to merge 🎉

#400 feat(web-app): breadcrumb and page header enhancements
  packages/icons/src/main/svg/64-backup.svg
  services/web-app/components/catalog-item/catalog-item.js
  services/web-app/components/catalog-item/catalog-item.module.scss
  services/web-app/components/hero/hero.module.scss
  services/web-app/components/page-breadcrumb/page-breadcrumb.module.scss
  services/web-app/components/page-header/page-header.js
  services/web-app/components/page-header/page-header.module.scss
  services/web-app/components/page-not-found/page-not-found.module.scss
  services/web-app/components/type-tag/index.js
  services/web-app/components/type-tag/type-tag.js
  services/web-app/components/type-tag/type-tag.module.scss
  services/web-app/data/nav-data.js
  services/web-app/data/type.js
  services/web-app/layouts/layout/layout.module.scss
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/assets/components.js
  services/web-app/pages/assets/functions.js
  services/web-app/pages/assets/libraries.js
  services/web-app/pages/assets/patterns.js
  services/web-app/pages/assets/templates.js
  services/web-app/styles/_variables.scss
  services/web-app/styles/vendor/_overrides.scss
  services/web-app/utils/schema.js
Labels: status: ready for review 👀

#314 feat: added esc working on focus
  services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.js
  services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.module.scss
  services/web-app/utils/use-focus.js
  services/web-app/utils/use-on-key.js
  services/web-app/utils/use-query-state.js
Labels: status: ready for review 👀

#315 Validate correct page number when affecting changes occur
  services/web-app/components/catalog/catalog.js
Labels: status: one more review 👀

#461 fix(web-app): change @carbon/styles imports for @carbon/react
  services/web-app/styles/vendor/_overrides.scss
Labels: status: ready for review 👀
