Repository carbon-design-system/carbon-platform, pull requests merged in 2022-08, with the labels that each got.

#1075 feat: storybook demo component
  services/web-app/components/mdx/components.js
  services/web-app/components/storybook-demo/index.js
  services/web-app/components/storybook-demo/storybook-demo.js
  services/web-app/components/storybook-demo/storybook-demo.module.scss
  services/web-app/pages/mdx/storybook-demo.mdx
  services/web-app/stories/mdx/storybook-demo.stories.js
Labels: status: ready to merge 🎉

#1086 fix(web-app): make library name clickable
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
Labels: status: ready to merge 🎉

#1096 feat(web-app): dashboard demo link updates
  packages/icons/src/main/svg/storybook.svg
  services/web-app/components/dashboard/dashboard.module.scss
  services/web-app/components/demo-links/demo-links.js
  services/web-app/components/demo-links/index.js
  services/web-app/layouts/layout/layout.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/pages.module.scss
Labels: status: ready to merge 🎉

#1097 fix(web-app): update library side nav and page heading
  services/web-app/lib/github.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js
Labels: status: ready to merge 🎉

#1112 feat(web-app): add design kit links to dashboard
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
Labels: status: ready to merge 🎉

#1032 feat: error handling ui components
  package-lock.json
  services/web-app/components/full-page-error/full-page-error.js
  services/web-app/components/full-page-error/full-page-error.module.scss
  services/web-app/components/full-page-error/index.js
  services/web-app/components/inline-error/index.js
  services/web-app/components/inline-error/inline-error.js
  services/web-app/components/inline-error/inline-error.module.scss
  services/web-app/components/inline-notification/inline-notification.module.scss
  services/web-app/components/page-not-found/page-not-found.module.scss
Labels: status: one more review 👀

#965 fix: white space margin
  services/web-app/layouts/layout/layout.module.scss
  services/web-app/pages/index/index.module.scss
  services/web-app/styles/_base.scss
Labels: status: one more review 👀

#1116 fix: code margin on grid page
  services/web-app/pages/elements/2x-grid/grid-demo.module.scss
  services/web-app/pages/elements/2x-grid/implementation.mdx
Labels: status: ready to merge 🎉

#1118 fix(web-app): remove style overrides content switcher
  services/web-app/components/color-token-table/color-token-table.js
  services/web-app/components/color-token-table/color-token-table.module.scss
Labels: status: ready to merge 🎉

#1111 feat(web-app): side nav ia updates
  services/web-app/data/nav-data.js
  services/web-app/data/type.js
  services/web-app/next.config.mjs
  services/web-app/pages/about-carbon/contact/index.mdx
  services/web-app/pages/about-carbon/faq/index.mdx
  services/web-app/pages/about-carbon/how-carbon-works.mdx
  services/web-app/pages/assets/components.js
  services/web-app/pages/assets/elements.js
  services/web-app/pages/assets/functions.js
  services/web-app/pages/assets/patterns.js
  services/web-app/pages/assets/templates.js
  services/web-app/pages/data-visualization/axes-and-labels.js
  services/web-app/pages/data-visualization/chart-anatomy.mdx
  services/web-app/pages/data-visualization/color-palettes.mdx
  services/web-app/pages/data-visualization/dashboards.js
  services/web-app/pages/data-visualization/get-started.js
  services/web-app/pages/data-visualization/index.js
  services/web-app/pages/data-visualization/legends.js
  services/web-app/pages/guidelines/accessibility/color.mdx
  services/web-app/pages/guidelines/accessibility/developers.js
  services/web-app/pages/guidelines/accessibility/keyboard.js
  services/web-app/pages/guidelines/accessibility/overview.mdx
  services/web-app/pages/guidelines/content/action-labels.mdx
  services/web-app/pages/guidelines/content/overview.js
  services/web-app/pages/guidelines/content/writing-style.js
  services/web-app/pages/index.js
  services/web-app/public/data/diskstore-aefb32f98217f9a4c7fd4711210f9f2f.json
  services/web-app/public/guidelines/accessibility/a11ybee.svg
  services/web-app/public/guidelines/accessibility/bee.svg
  services/web-app/public/guidelines/accessibility/color-accessibility-1.png
  services/web-app/public/guidelines/accessibility/color-accessibility-2.png
  services/web-app/public/guidelines/accessibility/color-contrast-icon.png
  services/web-app/public/guidelines/accessibility/high-contrast.png
  services/web-app/public/guidelines/accessibility/nocoffee.png
  services/web-app/public/guidelines/accessibility/stark.png
  services/web-app/public/guidelines/content/sentence_case_786.png
Labels: status: content review ✍️, status: visual review 🔍

#1113 feat(web-app): add framework icon and other frameworks to asset detail
  services/web-app/components/dashboard/dashboard.module.scss
  services/web-app/components/mdx-icon/mdx-icon.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.module.scss
Labels: status: one more review 👀

#1110 fix(web-app): library side nav style and spacing fix
  services/web-app/components/nav-secondary/nav-secondary.module.scss
Labels: status: visual review 🔍

#1128 feat(web-app): add related libraries to dashboard
  services/web-app/components/dashboard/dashboard.module.scss
  services/web-app/lib/github.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
Labels: status: one more review 👀

#784 feat: getting started page
  packages/icons/src/main/svg/24-adobe.svg
  packages/icons/src/main/svg/24-axure.svg
  packages/icons/src/main/svg/32-adobe.svg
  packages/icons/src/main/svg/32-axure.svg
  services/web-app/components/mdx-icon/mdx-icon.js
  services/web-app/data/nav-data.js
  services/web-app/pages/designing/get-started.mdx
  services/web-app/public/designing/get-started/CarbonEcosystem.png
  services/web-app/public/designing/get-started/KitDependancy.png
Labels: status: one more review 👀

#842 feat: filter data table
  services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.js
  services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.module.scss
  services/web-app/components/filterable-design-kit-table/index.js
  services/web-app/components/mdx/components.js
  services/web-app/data/design-kits.js
  services/web-app/data/teams.js
  services/web-app/lib/github.js
  services/web-app/pages/designing/get-started.mdx
Labels: status: ready to merge 🎉

#1134 fix: hot fixes for get started design page
  packages/resources/carbon.yml
  services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.js
  services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.module.scss
  services/web-app/data/design-kits.js
  services/web-app/data/nav-data.js
  services/web-app/pages/designing/get-started.mdx
  services/web-app/public/designing/get-started/CarbonEcosystem.png
  services/web-app/public/designing/get-started/CarbonSystem.png
Labels: status: ready to merge 🎉

#1137 feat(web-app): add anchor links to library detail page
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
Labels: status: ready to merge 🎉

#1139 fix(web-app): arrow icon color
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.module.scss
Labels: status: one more review 👀

#1143 fix: update and use teams data in design kits table
  packages/resources/carbon.yml
  services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.js
  services/web-app/data/design-kits.js
  services/web-app/data/teams.js
Labels: status: one more review 👀

#1145 fix(web-app): update side nav z-index to fix tab bg overlay with scrollbar
  services/web-app/layouts/layout/layout.module.scss
Labels: status: ready to merge 🎉

#1138 fix(web-app): dropdown border styles
  services/web-app/components/catalog-sort/catalog-sort.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.module.scss
Labels: status: one more review 👀

#1152 Remove Test MDX Component
  services/web-app/components/mdx/components.js
Labels: status: one more review 👀

#1149 fix(web-app): sass import order
  services/web-app/components/back-to-top/back-to-top.module.scss
  services/web-app/components/svg-libraries/svg-library.module.scss
  services/web-app/layouts/layout/layout.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.module.scss
  services/web-app/styles/vendor/_overrides.scss
Labels: status: ready to merge 🎉

#1157 fix(web-app): code snippet background bug
  services/web-app/components/code/code.js
Labels: status: one more review 👀

#1162 fix(web-app): scrollbar display on library nav
  services/web-app/components/nav-secondary/nav-secondary.module.scss
Labels: status: one more review 👀

#1161 fix(web-app): spacing across markdown components
  services/web-app/components/do-dont/do-dont.module.scss
  services/web-app/components/grid-transform/grid.module.scss
  services/web-app/components/markdown/image.module.scss
  services/web-app/components/markdown/markdown.module.scss
  services/web-app/components/markdown/ol.js
  services/web-app/components/markdown/ul.js
  services/web-app/components/page-tabs/page-tabs.module.scss
  services/web-app/components/title/title.js
  services/web-app/components/title/title.module.scss
  services/web-app/pages/elements/2x-grid/grid-demo.module.scss
Labels: status: ready for review 👀

#1159 fix(web-app): hide view asset doc button if no external docs
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
Labels: status: one more review 👀

#1151 feat: getting started page enhancements
  packages/resources/carbon.yml
  services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.js
  services/web-app/components/filterable-design-kit-table/filterable-design-kit-table.module.scss
  services/web-app/data/design-kits.js
  services/web-app/pages/designing/get-started.mdx
Labels: status: visual review 🔍

#1074 feat(web-app): use heading markdown components in web-app
  services/web-app/components/catalog-list/catalog-list.js
  services/web-app/components/catalog-list/catalog-list.module.scss
  services/web-app/components/glossary/glossary-list/glossary-list.js
  services/web-app/components/glossary/glossary-list/glossary-list.module.scss
  services/web-app/components/hero/hero.module.scss
  services/web-app/components/markdown/h1.js
  services/web-app/components/markdown/h2.js
  services/web-app/components/markdown/h3.js
  services/web-app/components/markdown/h4.js
  services/web-app/components/markdown/h5.js
  services/web-app/components/markdown/h6.js
  services/web-app/components/mdx-page/errors/full-page-error/full-page-error.js
  services/web-app/components/mdx-page/errors/full-page-error/full-page-error.module.scss
  services/web-app/components/page-not-found/page-not-found.js
  services/web-app/components/page-not-found/page-not-found.module.scss
  services/web-app/components/svg-libraries/icon-library/icon-category.js
  services/web-app/components/svg-libraries/no-result/no-result.js
  services/web-app/components/svg-libraries/pictogram-library/pictogram-category.js
  services/web-app/components/svg-libraries/svg-library.module.scss
  services/web-app/components/typeset-style/typeset-style.js
  services/web-app/components/typeset-style/typeset-style.module.scss
  services/web-app/pages/about-carbon/platform-roadmap.js
  services/web-app/pages/about-carbon/platform-roadmap.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/design-kits.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/stories/mdx/divider.stories.js
Labels: status: one more review 👀

#1169 feat: add additional demo link type other
  packages/api/src/main/data-graph/models/library.model.ts
  packages/schemas/carbon-resources.schema.json
  packages/schemas/internal/validation/asset-validation.schema.json
  packages/schemas/internal/validation/library-validation.schema.json
  services/web-app/components/demo-links/demo-links.js
  services/web-app/components/mdx-icon/mdx-icon.js
  services/web-app/pages/contributing/schema.mdx
Labels: status: one more review 👀

#1174 fix(web-app): active nav state
  services/web-app/components/nav-tree/nav-tree.js
Labels: status: one more review 👀

#1166 fix(web-app): render remotely loaded SVGs
  services/web-app/components/markdown/image.js
  services/web-app/lib/github.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/pages/[...page].js
  services/web-app/utils/string.js
Labels: status: one more review 👀

#1177 fix: copy update
  services/web-app/pages/about-carbon/how-carbon-works.mdx
Labels: status: one more review 👀

#1150 feat(web-app): update landing page to new design
  packages/icons/src/main/svg/start_designing_arrow.svg
  packages/icons/src/main/svg/start_dev_arrow.svg
  services/web-app/components/code/code.js
  services/web-app/components/divider/divider.js
  services/web-app/components/divider/divider.module.scss
  services/web-app/components/feature-card/feature-card.js
  services/web-app/components/feature-card/feature-card.module.scss
  services/web-app/components/hero/hero.js
  services/web-app/components/hero/hero.module.scss
  services/web-app/components/inline-notification/inline-notification.js
  services/web-app/components/markdown/h1.js
  services/web-app/components/markdown/h2.js
  services/web-app/components/markdown/h3.js
  services/web-app/components/markdown/h4.js
  services/web-app/components/markdown/h5.js
  services/web-app/components/markdown/h6.js
  services/web-app/components/markdown/markdown.module.scss
  services/web-app/components/markdown/ol.js
  services/web-app/components/markdown/p.js
  services/web-app/components/markdown/ul.js
  services/web-app/components/page-description/page-description.js
  services/web-app/components/page-header/page-header.module.scss
  services/web-app/components/title/title.js
  services/web-app/layouts/layout/layout.js
  services/web-app/pages/about-carbon/platform-roadmap.module.scss
  services/web-app/pages/index.js
  services/web-app/pages/index/images/assets-hero.png
  services/web-app/pages/index/images/assets-hero_mobile.png
  services/web-app/pages/index/images/carbon-react_max-lg.png
  services/web-app/pages/index/images/carbon-react_md.png
  services/web-app/pages/index/images/carbon-react_sm.png
  services/web-app/pages/index/images/chart-banner.png
  services/web-app/pages/index/images/ecosystem_max-md.png
  services/web-app/pages/index/images/ecosystem_sm.png
  services/web-app/pages/index/images/ibmdotcom_max-lg.png
  services/web-app/pages/index/images/ibmdotcom_md.png
  services/web-app/pages/index/images/ibmdotcom_sm.png
  services/web-app/pages/index/images/react-banner.png
  services/web-app/pages/index/images/roadmap_max-lg.png
  services/web-app/pages/index/images/roadmap_sm.png
  services/web-app/pages/index/index.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
Labels: status: visual review 🔍

#1173 feat(web-app): designKit inheritance
  services/web-app/lib/github.js
  services/web-app/public/data/diskstore-0b48cb8969f4527eb13dbabd812a85b3.json
  services/web-app/public/data/diskstore-1f77a223d3ea1c6f491f8e32c29151af.json
  services/web-app/public/data/diskstore-803c09b3d25cd96aeaf436301e06831c.json
  services/web-app/public/data/diskstore-957eae564b1fa3eeda8e95e7c0235e9f.json
  services/web-app/public/data/diskstore-c833257bac9ac6cb3acd4069efd09709.json
  services/web-app/public/data/diskstore-caa3013071fea132d34c2cdde53e38ed.json
Labels: status: ready for review 👀

#1178 fix: rewrite FAQ page
  services/web-app/pages/about-carbon/faq/index.mdx
Labels: status: ready to merge 🎉

#1184 feat(web-app): lock down iframe props
  services/web-app/components/preview/preview.js
  services/web-app/components/storybook-demo/storybook-demo.js
  services/web-app/components/video/video.js
Labels: status: one more review 👀

#1185 fix: add design kit descriptions
  packages/resources/carbon.yml
Labels: status: ready for review 👀

#1190 fix(web-app): update roadmap images on homepage
  services/web-app/pages/index.js
  services/web-app/pages/index/images/roadmap_max-lg.png
  services/web-app/pages/index/images/roadmap_sm.png
Labels: status: one more review 👀

#1188 fix: bugs found while indexing
  packages/schemas/carbon-resources.schema.json
  packages/schemas/internal/validation/asset-validation.schema.json
  services/web-app/components/dashboard/dashboard.module.scss
  services/web-app/lib/github.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js
  services/web-app/public/data/diskstore-8750b83cf2fd8f0059729b1932cdbb41.json
Labels: status: ready to merge 🎉

#1198 fix: get started spacing bug
  services/web-app/pages/designing/get-started.mdx
Labels: status: one more review 👀, status: ready for review 👀
