Repository carbon-design-system/carbon-platform, pull requests merged in 2022-09, with the labels that each got.

#1214 fix(icons): replace adobe xd icon
  packages/icons/src/main/svg/16-adobe-xd.svg
  packages/icons/src/main/svg/32-adobe-xd.svg
Labels: status: one more review 👀

#1222 add $ref guidance to schema docs
  services/web-app/pages/contributing/schema.mdx
Labels: status: one more review 👀

#1179 Flucca/feat/1015/add overview path
  packages/schemas/carbon-resources.schema.json
  packages/schemas/internal/validation/asset-validation.schema.json
  services/web-app/components/asset-details/asset-details.js
  services/web-app/components/asset-details/asset-details.module.scss
  services/web-app/components/asset-details/index.js
  services/web-app/components/assets-catalog/assets-catalog.js
  services/web-app/components/library-catalog-item/library-catalog-item.js
  services/web-app/components/library-catalog/library-catalog.js
  services/web-app/jsconfig.json
  services/web-app/lib/github.js
  services/web-app/pages/contributing/schema.mdx
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/[tab].js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/pages/[...page].js
  services/web-app/typedefs.js
  services/web-app/types.js
  services/web-app/utils/mdx.js
  services/web-app/utils/resources.js
  services/web-app/utils/schema.js
  services/web-app/utils/slug.js
Labels: status: ready for review 👀, status: ready to merge 🎉

#1203 fix(web-app): cache schema resolved references
  services/web-app/lib/file-cache.js
  services/web-app/lib/github.js
  services/web-app/public/data/diskstore-02691360a7312f68939445bc3854fb4c.json
  services/web-app/public/data/diskstore-0f19c11ed501ca68a0e753cd9d8af1db.json
  services/web-app/public/data/diskstore-13ffa9930514303f4ab65f133a72e146.json
  services/web-app/public/data/diskstore-1e773ba2350faf78b9e608c136632389.json
  services/web-app/public/data/diskstore-25dfef1775d8d11161e26585bd5198ad.json
  services/web-app/public/data/diskstore-4ab2b33cd24dcb99831b9971871191bb.json
  services/web-app/public/data/diskstore-53fa7d24f6cef85652c6e997d8275da7.json
  services/web-app/public/data/diskstore-5b04a3575c63cc12b2073de049eded46.json
  services/web-app/public/data/diskstore-5c71ac83223091fa2a5425b920d7f78c.json
  services/web-app/public/data/diskstore-66cf5e265ffdd60cbd2bb64921357969.json
  services/web-app/public/data/diskstore-72fb41c95a71fc13b0434b454f87af21.json
  services/web-app/public/data/diskstore-9168293c20114a3f92b06b5bb87b69a3.json
  services/web-app/public/data/diskstore-aefb32f98217f9a4c7fd4711210f9f2f.json
  services/web-app/public/data/diskstore-ba25bb30cf90859a879a69abc1687db1.json
  services/web-app/public/data/diskstore-c1ea2d1002565a952b21b582731f5454.json
  services/web-app/public/data/diskstore-cd3d44d0f671776e14db76fc4d316350.json
  services/web-app/public/data/diskstore-d96da38ab73500e58b55fb4fbf44c82b.json
  services/web-app/public/data/diskstore-de1e7e01e37f228a99a09593febc3c94.json
  services/web-app/public/data/diskstore-f905fc9f1a3a04aab121cf86061fb143.json
Labels: status: ready to merge 🎉

#1232 fix(web-app): add anchor element to tree nav
  services/web-app/components/nav-tree/nav-tree.js
  services/web-app/components/nav-tree/nav-tree.module.scss
Labels: status: ready to merge 🎉

#1231 fix(web-app): code snippet style bug
  services/web-app/components/code/code.module.scss
Labels: status: one more review 👀

#1255 fix(web-app): only include related library if not null and with content
  services/web-app/lib/github.js
Labels: status: one more review 👀

#1225 feat: add page redirects
  services/web-app/config/redirects.mjs
  services/web-app/data/nav-data.js
  services/web-app/data/remote-pages.js
  services/web-app/next.config.mjs
  services/web-app/pages/about-carbon/community-sites.mdx
  services/web-app/pages/about-carbon/help/contact/index.mdx
  services/web-app/pages/about-carbon/help/faq/index.mdx
  services/web-app/pages/contributing/documentation.mdx
  services/web-app/pages/migrating/guide/design.mdx
  services/web-app/pages/migrating/guide/develop.mdx
  services/web-app/public/about-carbon/community-sites/bee.svg
  services/web-app/public/about-carbon/community-sites/blog.svg
  services/web-app/public/about-carbon/community-sites/chat-bot.svg
  services/web-app/public/about-carbon/community-sites/data--1.svg
  services/web-app/public/about-carbon/community-sites/ibm-cloud.svg
  services/web-app/public/about-carbon/community-sites/iot--platform.svg
  services/web-app/public/about-carbon/community-sites/watson.svg
  services/web-app/public/migrating/guide/images/05_toast_context_608.gif
  services/web-app/public/migrating/guide/images/carbon.svg
  services/web-app/public/migrating/guide/images/carbon_2021-april-update.png
  services/web-app/public/migrating/guide/images/carbon_2021-beta-1.png
  services/web-app/public/migrating/guide/images/carbon_2021-beta-2.png
  services/web-app/public/migrating/guide/images/carbon_2021-beta-3.png
  services/web-app/public/migrating/guide/images/carbon_2021.png
  services/web-app/public/migrating/guide/images/color-implementation-compare-1.png
  services/web-app/public/migrating/guide/images/color-implementation-compare-2.png
  services/web-app/public/migrating/guide/images/color-implementation-compare.png
  services/web-app/public/migrating/guide/images/color-implementation-inline-1.png
  services/web-app/public/migrating/guide/images/color-implementation-layer-set-3.png
  services/web-app/public/migrating/guide/images/contained-tabs.png
  services/web-app/public/migrating/guide/images/light-or-dark-mode-1.png
  services/web-app/public/migrating/guide/images/light-or-dark-mode-2.png
  services/web-app/public/migrating/guide/images/medium-icon.svg
  services/web-app/public/migrating/guide/images/migrate-design-color-tokens.png
  services/web-app/public/migrating/guide/images/popover-usage-1.png
  services/web-app/public/migrating/guide/images/tooltip-usage-1.png
  services/web-app/public/migrating/guide/images/ui-shell-themes.png
  services/web-app/typedefs.js
  sonar-project.properties
Labels: status: one more review 👀

#1228 feat(web-app): add design kit library page
  packages/icons/src/main/svg/32-adobe-xd.svg
  packages/icons/src/main/svg/axure.svg
  packages/icons/src/main/svg/invision.svg
  services/web-app/components/mdx-icon/mdx-icon.js
  services/web-app/components/page-description/page-description.module.scss
  services/web-app/components/resource-card/resource-card.js
  services/web-app/components/resource-card/resource-card.module.scss
  services/web-app/data/design-kit-types.js
  services/web-app/data/design-tools.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/design-kits.js
Labels: status: waiting on design review 🎨

#1262 fix(web-app): code snippet width at md breakpoint
  services/web-app/components/code/code.module.scss
Labels: status: one more review 👀

#1263 fix(web-app): revalidate statically generated pages, add cache for SSG
  services/web-app/pages/[...remote-mdx-path].js
  services/web-app/pages/assets/components.js
  services/web-app/pages/assets/functions.js
  services/web-app/pages/assets/patterns.js
  services/web-app/pages/assets/templates.js
  services/web-app/pages/data-visualization/index.js
  services/web-app/pages/designing/get-started.mdx
  services/web-app/pages/elements/icons/library.mdx
  services/web-app/pages/elements/pictograms/library.mdx
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/design-kits.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/libraries/index.js
Labels: status: one more review 👀, status: ready for review 👀

#1264 fix(web-app): fixes undefined maintainer in library
  services/web-app/components/asset-catalog-item/asset-catalog-item.js
  services/web-app/data/libraries.mjs
Labels: status: one more review 👀

#1243 fix(web-app): add multiple logging statements, refresh cached files
  services/web-app/lib/file-cache.js
  services/web-app/lib/github.js
Labels: status: ready to merge 🎉

#1282 fix: adobe xd icon
  packages/icons/src/main/svg/16-adobe-xd.svg
  services/web-app/typedefs.js
Labels: status: one more review 👀

#1283 fix(web-app): gracefully handle prismjs crashes
  .eslintignore
  .lintstagedrc.js
  .prettierignore
  package-lock.json
  packages/mdx-components/src/main/anchor-links/anchor-link.tsx
  packages/mdx-components/src/main/anchor-links/anchor-links.tsx
  packages/mdx-components/src/main/color-block/color-block.tsx
  packages/mdx-components/src/main/index.ts
  services/web-app/components/code/carbon-theme.js
  services/web-app/components/code/code.js
  services/web-app/components/code/code.module.scss
  services/web-app/components/mdx/components.js
  services/web-app/components/page-description/page-description.module.scss
  services/web-app/package.json
  services/web-app/pages/_app.js
  services/web-app/public/vendor/prismjs/prism.js
  services/web-app/public/vendor/prismjs/prism.min.js
  services/web-app/styles/_prism-theme.scss
  services/web-app/styles/styles.scss
Labels: status: ready to merge 🎉

#1334 fix(web-app): set unique id for treeview nodes
  services/web-app/components/nav-tree/nav-tree.js
Labels: status: ready for review 👀, status: ready to merge 🎉

#1332 fix(web-app): table span 8 col at tablet
  services/web-app/components/page-table/page-table.js
Labels: status: ready to merge 🎉

#1335 fix(web-app): filter text font size
  services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.module.scss
Labels: status: one more review 👀, status: ready for review 👀

#1336 fix(web-app): update design kit catalog icon
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/design-kits.js
Labels: status: one more review 👀, status: ready for review 👀

#1343 fix(web-app): remove border-top resource card on mobile
  services/web-app/components/resource-card/resource-card-group.module.scss
Labels: status: ready to merge 🎉

#1344 fix(web-app): border subtle in catalog search
  services/web-app/components/catalog-search/catalog-search.module.scss
Labels: status: one more review 👀

#1337 fix(web-app): broken links
  services/web-app/pages/about-carbon/how-carbon-works.mdx
  services/web-app/pages/designing/axure.mdx
  services/web-app/pages/designing/get-started.mdx
  services/web-app/pages/designing/sketch.mdx
  services/web-app/pages/developing/index.mdx
  services/web-app/pages/elements/icons/contribute.mdx
  services/web-app/pages/elements/pictograms/contribute.mdx
  services/web-app/pages/guidelines/accessibility/overview.mdx
  services/web-app/pages/index.js
Labels: status: ready to merge 🎉

#1345 fix(resources): download action in sketch DKs
  packages/resources/carbon.yml
Labels: status: ready to merge 🎉

#1346 fix(resources): link to new figma kit for dotcom white theme
  packages/resources/carbon.yml
Labels: status: ready to merge 🎉

#1338 Page load improvements
  docs/docker.md
  services/web-app/components/article-card/article-card.js
  services/web-app/components/asset-catalog-item/asset-catalog-item.js
  services/web-app/components/asset-details/asset-details.js
  services/web-app/components/dashboard/dashboard-item.js
  services/web-app/components/feature-card/feature-card.js
  services/web-app/components/library-catalog-item/library-catalog-item.js
  services/web-app/components/mini-card/mini-card.js
  services/web-app/components/nav-primary/nav-primary.js
  services/web-app/components/nav-secondary/nav-secondary.js
  services/web-app/components/nav-tree/nav-tree.js
  services/web-app/components/page-breadcrumb/page-breadcrumb.js
  services/web-app/components/page-tabs/page-tabs.js
  services/web-app/components/resource-card/resource-card.js
  services/web-app/components/with-loading/index.js
  services/web-app/components/with-loading/with-loading.js
  services/web-app/layouts/layout/layout.js
  services/web-app/lib/github.js
  services/web-app/pages/[...remote-mdx-path].js
  services/web-app/pages/design-kits.js
  services/web-app/pages/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/[tab].js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/design-kits.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/pages/[...page].js
Labels: status: ready to merge 🎉

#1349 fix(web-app): remove anchor links from homepage h2
  services/web-app/pages/index.js
Labels: status: one more review 👀, status: ready for review 👀

#1351 fix(web-app): sort by left padding on asset list
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.module.scss
Labels: status: one more review 👀, status: ready for review 👀

#1352 1290 add yourlearning icon to mdxicon component
  packages/icons/src/main/svg/yourlearning.svg
  services/web-app/components/mdx-icon/mdx-icon.js
Labels: status: one more review 👀, status: ready for review 👀

#1354 fix(web-app): make breadcrumb link inline
  services/web-app/components/page-breadcrumb/page-breadcrumb.js
  services/web-app/components/page-breadcrumb/page-breadcrumb.module.scss
Labels: status: ready to merge 🎉

#1353 fix(web-app): focus state for catalog
  services/web-app/components/design-kit-catalog-item/design-kit-catalog-item.module.scss
Labels: status: one more review 👀, status: ready for review 👀

#1348 fix(web-app): spacing bugs
  services/web-app/components/color-palette/color-palette.module.scss
  services/web-app/components/divider/divider.module.scss
  services/web-app/components/do-dont/do-dont.module.scss
  services/web-app/components/markdown/markdown.module.scss
  services/web-app/components/page-table/page-table.js
  services/web-app/components/page-table/page-table.module.scss
  services/web-app/pages/data-visualization/color-palettes.mdx
  services/web-app/pages/data-visualization/dataviz.module.scss
Labels: status: ready to merge 🎉

#1356 feat: add loading page with skeletons
  services/web-app/components/nav-primary/nav-primary.js
  services/web-app/components/nav-primary/nav-primary.module.scss
  services/web-app/components/nav-secondary/nav-secondary.js
  services/web-app/components/nav-secondary/nav-secondary.module.scss
  services/web-app/components/page-header/page-header.js
  services/web-app/components/page-header/page-header.module.scss
  services/web-app/components/page-loading/index.js
  services/web-app/components/page-loading/page-loading.js
  services/web-app/components/page-loading/page-loading.module.scss
  services/web-app/components/with-loading/with-loading.js
  services/web-app/pages/[...remote-mdx-path].js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/[tab].js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/design-kits.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/pages/[...page].js
Labels: status: one more review 👀

#1359 fix(web-app): remove top border in library catalog first item
  services/web-app/components/library-catalog-item/library-catalog-item.js
  services/web-app/components/library-catalog-item/library-catalog-item.module.scss
  services/web-app/components/library-catalog/library-catalog.js
Labels: status: ready to merge 🎉

#1358 fix(web-app): open nav links with keyboard
  services/web-app/components/nav-tree/nav-tree.js
Labels: status: ready to merge 🎉

#1376 ci: add deploy storybook action
  .github/workflows/deploy-storybook.yml
Labels: status: one more review 👀
