Repository carbon-design-system/carbon-platform, pull requests merged in 2022-05, with the labels that each got.

#671 fix: tabs sticky and mobile bug
  services/web-app/components/page-tabs/page-tabs.js
  services/web-app/components/page-tabs/page-tabs.module.scss
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].module.scss
Labels: status: ready for review 👀

#660 feat(web-app): add typescaletable & typeweight mdx components
  services/web-app/components/accordion/accordion.module.scss
  services/web-app/components/anchor-links/anchor-links.module.scss
  services/web-app/components/mdx/components.js
  services/web-app/components/type/index.js
  services/web-app/components/type/type-scale-table.js
  services/web-app/components/type/type-scale.module.scss
  services/web-app/components/type/type-weight.js
  services/web-app/components/type/type-weight.module.scss
  services/web-app/pages/mdx/index.mdx
  services/web-app/pages/mdx/type.mdx
  services/web-app/stories/components/type-scale.stories.js
  services/web-app/stories/components/type-weight.stories.js
Labels: status: ready to merge 🎉

#622 feat(web-app): add mdx page table
  services/web-app/components/mdx/components.js
  services/web-app/components/page-table/index.js
  services/web-app/components/page-table/page-table.js
  services/web-app/components/page-table/page-table.module.scss
  services/web-app/pages/mdx/table.mdx
Labels: status: ready to merge 🎉

#623 feat(web-app): add preview mdx component
  services/web-app/components/mdx/components.js
  services/web-app/components/preview/index.js
  services/web-app/components/preview/preview.js
  services/web-app/components/preview/preview.module.scss
  services/web-app/pages/mdx/preview.mdx
  services/web-app/stories/mdx/preview.stories.js
Labels: status: one more review 👀

#664 feat(web-app): add typesetstyle component
  package-lock.json
  services/web-app/components/mdx/components.js
  services/web-app/components/tabs/tabs.js
  services/web-app/components/typeset-style/index.js
  services/web-app/components/typeset-style/input-range.js
  services/web-app/components/typeset-style/sticky-container.js
  services/web-app/components/typeset-style/typeset-example.js
  services/web-app/components/typeset-style/typeset-example.module.scss
  services/web-app/components/typeset-style/typeset-style.js
  services/web-app/components/typeset-style/typeset-style.module.scss
  services/web-app/data/type-scale.js
  services/web-app/data/type-sets.js
  services/web-app/package.json
  services/web-app/pages/mdx/index.mdx
  services/web-app/pages/mdx/typesetstyle.mdx
  services/web-app/stories/components/typeset-style.stories.js
Labels: status: one more review 👀

#670 feat(web-app): glossary component
  package-lock.json
  services/web-app/components/glossary/glossary-list/glossary-list.js
  services/web-app/components/glossary/glossary-list/glossary-list.module.scss
  services/web-app/components/glossary/glossary-list/index.js
  services/web-app/components/glossary/glossary-nav/glossary-nav.js
  services/web-app/components/glossary/glossary-nav/glossary-nav.module.scss
  services/web-app/components/glossary/glossary-nav/index.js
  services/web-app/components/glossary/glossary.js
  services/web-app/components/glossary/index.js
  services/web-app/components/mdx/components.js
  services/web-app/data/glossary.js
  services/web-app/package.json
  services/web-app/pages/mdx/glossary.mdx
  services/web-app/pages/mdx/index.mdx
  services/web-app/stories/components/glossary.stories.js
Labels: status: one more review 👀

#668 feat(web-app): add color token table component
  services/web-app/components/color-token-table/color-token-table.js
  services/web-app/components/color-token-table/color-token-table.module.scss
  services/web-app/components/color-token-table/index.js
  services/web-app/components/mdx/components.js
  services/web-app/components/typeset-style/typeset-style.module.scss
  services/web-app/data/color-tokens.js
  services/web-app/pages/mdx/color-token-table.mdx
  services/web-app/stories/components/color-token-table.stories.js
Labels: status: one more review 👀

#667 feat: carbon angular index test
  services/web-app/data/libraries.js
  services/web-app/public/assets/thumbnails/icon.svg
  services/web-app/public/assets/thumbnails/input.svg
  services/web-app/public/assets/thumbnails/list.svg
  services/web-app/public/assets/thumbnails/radio.svg
  services/web-app/public/assets/thumbnails/skeleton.svg
  services/web-app/public/assets/thumbnails/table.svg
  services/web-app/public/assets/thumbnails/time-picker-select.svg
  services/web-app/public/data/diskstore-063a667c5f0912e957daa90f21a4e9b2.json
  services/web-app/public/data/diskstore-0873c18bd05c3ba0fa3db931fba13d31.json
  services/web-app/public/data/diskstore-0b0ed2a1a73c63f2069355393f1075fc.json
  services/web-app/public/data/diskstore-0bcac8320ccbfc81abf01207cfb7df95.json
  services/web-app/public/data/diskstore-0dd51f0e243364cf5642b6c3a881af1c.json
  services/web-app/public/data/diskstore-0f9dd16e0ef8614d2256e20829d1fa43.json
  services/web-app/public/data/diskstore-1ec82100a16173d21e39bf95f7e0367b.json
  services/web-app/public/data/diskstore-288142469b5e3d30a4674b1dbbf1a17f.json
  services/web-app/public/data/diskstore-2b5a79213d721a6e220d6f3911cb1b1a.json
  services/web-app/public/data/diskstore-2ee63a8757b45e636e8a4905f9185ed9.json
  services/web-app/public/data/diskstore-323993b34c1aaf5d0947a3b91a17ddd0.json
  services/web-app/public/data/diskstore-37837d1c9093dfc9524d98c0e66d73ee.json
  services/web-app/public/data/diskstore-3b63276c732e80f8500a9abbf30f6b6a.json
  services/web-app/public/data/diskstore-3ca16770ba9e53b54e2f08485cb95390.json
  services/web-app/public/data/diskstore-3d7a7ebddbd3aefb31b7a3f4e8661b67.json
  services/web-app/public/data/diskstore-4111b5d1f13c7f558ac610b9a6e8a80b.json
  services/web-app/public/data/diskstore-42cd28b422e03a8b188dfa116fdf61b3.json
  services/web-app/public/data/diskstore-4404e0cd09597e7812c4e602bd776516.json
  services/web-app/public/data/diskstore-45ef8b6b38eee3dc08db89635c850886.json
  services/web-app/public/data/diskstore-4a459c0f3254bc8a48ae4c7e0107d995.json
  services/web-app/public/data/diskstore-4ed5495f35de3d016b5e8a12a7cdc15f.json
  services/web-app/public/data/diskstore-51e653bce36c52ed40512269933866ff.json
  services/web-app/public/data/diskstore-5328a467caca6ccd75064714e9adc538.json
  services/web-app/public/data/diskstore-5fb9a2bf92f83ce66048d262d1f1d38a.json
  services/web-app/public/data/diskstore-6e526330d17051d796e79d165799cee9.json
  services/web-app/public/data/diskstore-7addac389ca6ecb344f6523792edae01.json
  services/web-app/public/data/diskstore-7e428bbdd63585d2e822d3f4b08b2ac9.json
  services/web-app/public/data/diskstore-852f2b2f0a144cc6fa1a521764a35531.json
  services/web-app/public/data/diskstore-85351f2d3451bff0f04ed605f52914c5.json
  services/web-app/public/data/diskstore-8cbc700c181adebe9f9f7b2abbb4bf9a.json
  services/web-app/public/data/diskstore-9181eb0a959a1dc5e84c2cb2b3e5e10e.json
  services/web-app/public/data/diskstore-95a442cd18af1f0acb7bd34a91f40d6b.json
  services/web-app/public/data/diskstore-9915dabac1ae609043540b9b4b59d9b7.json
  services/web-app/public/data/diskstore-a22a6f73533df2e7a3ff8d5fecb550e5.json
  services/web-app/public/data/diskstore-afedb226242b79c3e5bce7f704d81750.json
  services/web-app/public/data/diskstore-b0157a5f6fa7327247ea2d5f5dc3b03d.json
  services/web-app/public/data/diskstore-bb06e355476197b98f0ef3576e8996f2.json
  services/web-app/public/data/diskstore-bb2fce769af6c6aef39fbd96ebb569ca.json
  services/web-app/public/data/diskstore-bda5a8cbb3eecfbe365e7ae36ef0c528.json
  services/web-app/public/data/diskstore-c0d2d8ca5f210dec5857c127a9ec6b4d.json
  services/web-app/public/data/diskstore-c488c74039a96570fdf1c1282314ce2d.json
  services/web-app/public/data/diskstore-d7baffd079288d045f75866c0bbc8063.json
  services/web-app/public/data/diskstore-dd28e8b274c1e2f171141a3c4ade5823.json
  services/web-app/public/data/diskstore-e59dc11c051e4153a96c95226f9e76da.json
  services/web-app/public/data/diskstore-e95c57679e4eb65b19c62ee6eb6cd8b0.json
  services/web-app/public/data/diskstore-e9a0cdf42a2ba0fec222bcd357ccb637.json
  services/web-app/public/data/diskstore-ea9312322798350eaf7a3a5d029087a8.json
  services/web-app/public/data/diskstore-ee93f7862d2175789208d74dc776a7fb.json
  services/web-app/public/data/diskstore-f9f5fbdf522d27bcd498825f0dc53efd.json
Labels: status: ready to merge 🎉

#682 feat: index carbon components vue test
  services/web-app/data/libraries.js
  services/web-app/public/data/diskstore-0a92b2eb1987b5bbad6c5b3457484c31.json
  services/web-app/public/data/diskstore-103a7ed84238219f2203ffcb48fdf4f5.json
  services/web-app/public/data/diskstore-1fb1fa96b5875dec84643208a446f379.json
  services/web-app/public/data/diskstore-85945c4a4586f9f5d725647a2ea49894.json
  services/web-app/public/data/diskstore-9a0ed2f30857af64934ba7c0640d07a0.json
  services/web-app/public/data/diskstore-d94d31c6550349b336591dcdec46318d.json
Labels: status: one more review 👀

#681 feat(web-app): mdx icon component
  packages/icons/src/main/svg/64-patterns.svg
  packages/icons/src/main/svg/codesandbox.svg
  packages/icons/src/main/svg/figma.svg
  packages/icons/src/main/svg/illustrator.svg
  packages/icons/src/main/svg/medium.svg
  packages/icons/src/main/svg/npm.svg
  packages/icons/src/main/svg/sketch.svg
  packages/icons/src/main/svg/storybook.svg
  services/web-app/components/mdx-icon/icons/angular.png
  services/web-app/components/mdx-icon/icons/ase.png
  services/web-app/components/mdx-icon/icons/figma.svg
  services/web-app/components/mdx-icon/icons/react.png
  services/web-app/components/mdx-icon/icons/sass.png
  services/web-app/components/mdx-icon/icons/vue.png
  services/web-app/components/mdx-icon/icons/webcomponents.png
  services/web-app/components/mdx-icon/index.js
  services/web-app/components/mdx-icon/mdx-icon.js
  services/web-app/components/mdx-icon/mdx-icon.module.scss
  services/web-app/components/mdx/components.js
  services/web-app/pages/mdx/index.mdx
  services/web-app/pages/mdx/mdx-icon.mdx
  services/web-app/stories/mdx/mdx-icon.stories.js
Labels: status: ready for review 👀

#669 feat: document mdx components in storybook
  services/web-app/components/art-direction/art-direction.js
  services/web-app/components/article-card/article-card.js
  services/web-app/components/article-card/article-card.module.scss
  services/web-app/components/aside/aside.js
  services/web-app/components/aside/aside.module.scss
  services/web-app/components/caption/caption.js
  services/web-app/components/caption/caption.module.scss
  services/web-app/components/color-token-table/color-token-table.module.scss
  services/web-app/components/do-dont/do-dont-row.js
  services/web-app/components/do-dont/do-dont.js
  services/web-app/components/do-dont/do-dont.module.scss
  services/web-app/components/gif-player/gif-player.js
  services/web-app/components/gif-player/index.js
  services/web-app/components/inline-notification/inline-notification.js
  services/web-app/components/inline-notification/inline-notification.module.scss
  services/web-app/components/page-description/page-description.js
  services/web-app/components/page-description/page-description.module.scss
  services/web-app/components/profile/profile.js
  services/web-app/components/profile/profile.module.scss
  services/web-app/components/resource-card/resource-card.js
  services/web-app/components/tabs/tabs.js
  services/web-app/components/title/title.js
  services/web-app/components/title/title.module.scss
  services/web-app/components/video/index.js
  services/web-app/components/video/video.js
  services/web-app/components/video/video.module.scss
  services/web-app/pages/mdx/gif-player.mdx
  services/web-app/pages/mdx/index.mdx
  services/web-app/public/mdx/cloud.gif
  services/web-app/public/mdx/cloud.jpg
  services/web-app/stories/mdx/art-direction.stories.js
  services/web-app/stories/mdx/article-card.stories.js
  services/web-app/stories/mdx/aside.stories.js
  services/web-app/stories/mdx/caption.stories.js
  services/web-app/stories/mdx/do-dont.stories.js
  services/web-app/stories/mdx/gif-player.stories.js
  services/web-app/stories/mdx/inline-notification.stories.js
  services/web-app/stories/mdx/page-description.stories.js
  services/web-app/stories/mdx/profile.stories.js
  services/web-app/stories/mdx/resource-card.stories.js
  services/web-app/stories/mdx/tabs.stories.js
  services/web-app/stories/mdx/title.stories.js
  services/web-app/stories/mdx/video.stories.js
Labels: status: one more review 👀

#638 feat(web-app): migrate icons and pictograms library
  .npmrc
  package-lock.json
  packages/icons/src/main/svg/32-illustrator.svg
  services/web-app/components/inline-notification/inline-notification.js
  services/web-app/components/mdx/components.js
  services/web-app/components/svg-libraries/action-bar/action-bar.js
  services/web-app/components/svg-libraries/action-bar/action-bar.module.scss
  services/web-app/components/svg-libraries/action-bar/index.js
  services/web-app/components/svg-libraries/filter-row/filter-row.js
  services/web-app/components/svg-libraries/filter-row/index.js
  services/web-app/components/svg-libraries/icon-library/icon-category.js
  services/web-app/components/svg-libraries/icon-library/icon-library.js
  services/web-app/components/svg-libraries/icon-library/index.js
  services/web-app/components/svg-libraries/library-provider.js
  services/web-app/components/svg-libraries/no-result/index.js
  services/web-app/components/svg-libraries/no-result/no-result.js
  services/web-app/components/svg-libraries/pictogram-library/index.js
  services/web-app/components/svg-libraries/pictogram-library/pictogram-category.js
  services/web-app/components/svg-libraries/pictogram-library/pictogram-library.js
  services/web-app/components/svg-libraries/svg-card/index.js
  services/web-app/components/svg-libraries/svg-card/svg-card.js
  services/web-app/components/svg-libraries/svg-library.module.scss
  services/web-app/package.json
  services/web-app/pages/mdx/icons.mdx
  services/web-app/pages/mdx/pictograms.mdx
  services/web-app/stories/components/icon-library.stories.js
  services/web-app/stories/components/pictogram-library.stories.js
  services/web-app/utils/use-column-count.js
  services/web-app/utils/use-intersection-observer.js
  services/web-app/utils/use-sticky.js
Labels: status: one more review 👀

#710 fix(web-app): mdx tab bugs
  services/web-app/components/tabs/tabs.js
  services/web-app/components/tabs/tabs.module.scss
Labels: status: ready to merge 🎉

#715 fix(web-app): set correct page header height with tabs
  services/web-app/components/mdx-wrapper/mdx-wrapper.js
  services/web-app/components/page-header/page-header.js
  services/web-app/components/page-header/page-header.module.scss
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].js
  services/web-app/pages/mdx/code.mdx
Labels: status: one more review 👀

#718 fix(web-app): update dashboard card border
  services/web-app/components/dashboard/dashboard-item.js
  services/web-app/components/dashboard/dashboard-item.module.scss
  services/web-app/components/dashboard/dashboard.module.scss
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/assets/index.js
Labels: status: ready to merge 🎉

#716 fix(web-app): color palette grid alignment
  services/web-app/components/color-palette/color-palette.js
  services/web-app/components/color-palette/color-palette.module.scss
Labels: status: one more review 👀

#719 fix(web-app): page title descender clipped
  services/web-app/components/page-header/page-header.module.scss
Labels: status: ready to merge 🎉

#724 feat(web-app): treeview integration with sidenav
  services/web-app/components/nav-library/nav-library.js
  services/web-app/components/nav-main/nav-main.js
  services/web-app/components/nav-main/nav-main.module.scss
  services/web-app/components/nav-tree/nav-tree.js
  services/web-app/components/nav-tree/nav-tree.module.scss
  services/web-app/data/nav-data.js
Labels: status: one more review 👀

#738 fix(web-app): tabs clickable area
  services/web-app/components/page-tabs/page-tabs.module.scss
Labels: status: one more review 👀

#741 [TEST] fix: update thumbnails
  services/web-app/public/assets/thumbnails/aspect-ratio.svg
  services/web-app/public/assets/thumbnails/breadcrumb.svg
  services/web-app/public/assets/thumbnails/button-group.svg
  services/web-app/public/assets/thumbnails/button.svg
  services/web-app/public/assets/thumbnails/call-to-action.svg
  services/web-app/public/assets/thumbnails/error-boundary.svg
  services/web-app/public/assets/thumbnails/link-with-icon.svg
  services/web-app/public/assets/thumbnails/link.svg
  services/web-app/public/assets/thumbnails/list.svg
  services/web-app/public/assets/thumbnails/local-storage.svg
  services/web-app/public/assets/thumbnails/ordered-list.svg
  services/web-app/public/assets/thumbnails/pagination-nav.svg
  services/web-app/public/assets/thumbnails/progress-bar.svg
  services/web-app/public/assets/thumbnails/recursive-list.svg
  services/web-app/public/assets/thumbnails/time-picker-select.svg
  services/web-app/public/assets/thumbnails/time-picker.svg
  services/web-app/public/assets/thumbnails/truncate.svg
  services/web-app/public/assets/thumbnails/unordered-list.svg
  services/web-app/public/assets/thumbnails/unstable-heading.svg
  services/web-app/public/assets/thumbnails/unstable-text.svg
Labels: status: ready to merge 🎉

#753 fix(web-app): add teams pictograms and use in detail pages
  packages/icons/src/main/svg/64-carbon-for-ibm-dotcom.svg
  packages/icons/src/main/svg/64-carbon-for-ibm-products.svg
  packages/icons/src/main/svg/64-carbon.svg
  packages/icons/src/main/svg/64-cloud.svg
  packages/icons/src/main/svg/64-community.svg
  packages/icons/src/main/svg/64-security.svg
  packages/icons/src/main/svg/64-watson.svg
  services/web-app/data/teams.js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js
Labels: status: one more review 👀

#771 feat: add library asset description
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js
Labels: status: ready to merge 🎉

#772 fix(web-app): remove smooth scroll when routing to pages
  services/web-app/pages/_app.js
  services/web-app/styles/_base.scss
Labels: status: ready to merge 🎉

#749 feat: mobile nav bugs
  package-lock.json
  services/web-app/components/nav-library/nav-library.js
  services/web-app/components/nav-library/nav-library.module.scss
  services/web-app/components/nav-main/nav-main.js
  services/web-app/layouts/layout/layout.js
Labels: status: ready to merge 🎉

#778 feat(web-app): mini card component
  package-lock.json
  services/web-app/components/card-group/card-group.js
  services/web-app/components/card-group/card-group.module.scss
  services/web-app/components/card-group/index.js
  services/web-app/components/mdx/components.js
  services/web-app/components/mini-card/index.js
  services/web-app/components/mini-card/mini-card.js
  services/web-app/components/mini-card/mini-card.module.scss
  services/web-app/pages/mdx/index.mdx
  services/web-app/pages/mdx/mini-card.mdx
  services/web-app/pages/mdx/resource-card.mdx
  services/web-app/stories/mdx/mini-card.stories.js
  services/web-app/stories/mdx/resource-card.stories.js
Labels: status: one more review 👀

#774 feat: add nav data to schema
  docs/resource-schemas.md
  packages/schemas/carbon-resources.schema.json
  packages/schemas/internal/validation/library-validation.schema.json
Labels: status: ready to merge 🎉
