Repository carbon-design-system/carbon-platform, pull requests merged in 2022-10, with the labels that each got.

#1379 fix: update platform roadmap
  services/web-app/pages/about-carbon/platform-roadmap.js
Labels: status: ready to merge 🎉

#1362 fix(web-app): remove nav active state from section headings
  services/web-app/components/nav-tree/nav-tree.module.scss
Labels: status: one more review 👀

#1373 feat(web-app): add banner component
  services/web-app/components/banner/banner.js
  services/web-app/components/banner/banner.module.scss
  services/web-app/components/banner/index.js
  services/web-app/layouts/layout/layout.js
Labels: status: ready to merge 🎉

#1407 feat(web-app): add global content wrapper for consistent spacing
  services/web-app/components/asset-details/asset-details.js
  services/web-app/components/asset-details/asset-details.module.scss
  services/web-app/components/content-wrapper/content-wrapper.js
  services/web-app/components/content-wrapper/content-wrapper.module.scss
  services/web-app/components/content-wrapper/index.js
  services/web-app/components/mdx-page/mdx-page.js
  services/web-app/components/svg-libraries/svg-library.module.scss
  services/web-app/layouts/layout/layout.js
  services/web-app/pages/about-carbon/platform-roadmap.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/[tab].js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/[tab].module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/design-kits.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/libraries/index.js
Labels: status: ready to merge 🎉

#1383 1123 common mdx error documentation updates
  services/web-app/pages/common-mdx-errors.mdx
  services/web-app/pages/common-mdx-errors/index.js
  services/web-app/pages/common-mdx-errors/index.module.scss
  services/web-app/utils/mdx.js
Labels: status: ready to merge 🎉

#1402 fix: update site contacts
  packages/icons/src/main/svg/32-discord.svg
  packages/icons/src/main/svg/32-slack.svg
  services/web-app/components/footer/footer.js
  services/web-app/components/mdx-icon/mdx-icon.js
  services/web-app/pages/about-carbon/articles.mdx
  services/web-app/pages/about-carbon/help/contact/index.mdx
Labels: status: ready to merge 🎉

#1441 fix(web-app): dodont and image spacing bugs
  services/web-app/components/do-dont/do-dont.module.scss
  services/web-app/components/markdown/image.module.scss
Labels: status: ready to merge 🎉

#1428 refactor(web-app): use nav for tabs instead of carbon tabs
  services/web-app/components/mdx-page/mdx-page.js
  services/web-app/components/page-tabs/page-tabs.js
  services/web-app/components/page-tabs/page-tabs.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/[tab].js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/[tab].module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
Labels: status: one more review 👀, status: ready for review 👀

#1452 fix: update design kit dependencies image
  services/web-app/pages/designing/get-started.mdx
  services/web-app/public/designing/get-started/KitDependancy.png
  services/web-app/public/designing/get-started/KitDependencies.png
Labels: status: one more review 👀

#1444 fix(web-app): side nav homepage mobile position
  services/web-app/components/banner/banner.module.scss
Labels: status: one more review 👀

#1453 fix(web-app): catalog view icon hover and focus stlye fix
  services/web-app/components/catalog-sort/catalog-sort.module.scss
Labels: status: one more review 👀

#1455 fix(web-app): sidenav, keep active item on parent selection
  services/web-app/components/nav-tree/nav-tree.js
Labels: status: one more review 👀
