Repository carbon-design-system/carbon-platform, pull requests merged in 2022-06, with the labels that each got.

#795 feat(web-app): add image wrapper component for fixed images
  services/web-app/components/image-wrapper/image-wrapper.js
  services/web-app/components/image-wrapper/image-wrapper.module.scss
  services/web-app/components/image-wrapper/index.js
  services/web-app/components/mdx/components.js
  services/web-app/pages/mdx/image-wrapper.mdx
  services/web-app/pages/mdx/index.mdx
  services/web-app/public/mdx/accordion-style-3.png
  services/web-app/stories/mdx/image-wrapper.stories.js
Labels: status: one more review 👀

#790 feat(web-app): update collection page header
  services/web-app/data/type.js
  services/web-app/pages/assets/data-visualization.js
Labels: status: one more review 👀

#789 fix(web-app): shorten tag display names
  services/web-app/data/tags.js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/library-assets/index.js
  services/web-app/utils/schema.js
Labels: status: one more review 👀

#788 feat(web-app): add developing page
  packages/icons/src/main/svg/js.svg
  packages/icons/src/main/svg/npm.svg
  packages/icons/src/main/svg/svelte.svg
  packages/icons/src/main/svg/vue.svg
  services/web-app/components/mdx-icon/icons/codepen.png
  services/web-app/components/mdx-icon/mdx-icon.js
  services/web-app/components/mdx-icon/mdx-icon.module.scss
  services/web-app/data/nav-data.js
  services/web-app/pages/developing/index.mdx
  services/web-app/public/developing/carbon-devtools-extension.png
  services/web-app/public/developing/carbon-ecosystem.png
  services/web-app/public/developing/color-contrast-icon.png
Labels: status: one more review 👀

#808 fix: filter font and tag fonts
  services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.module.scss
Labels: status: one more review 👀

#812 fix: sponsor icons
  packages/icons/src/main/svg/24-carbon-for-ibm-dotcom.svg
  packages/icons/src/main/svg/24-carbon-for-ibm-products.svg
  services/web-app/components/catalog-item/catalog-item.module.scss
  services/web-app/data/teams.js
Labels: status: ready to merge 🎉

#787 fix(web-app): show library name/version inside nav, sidenav refactor
  services/web-app/components/mdx-wrapper/mdx-wrapper.js
  services/web-app/components/nav-library/nav-library.js
  services/web-app/components/nav-primary/index.js
  services/web-app/components/nav-primary/nav-primary.js
  services/web-app/components/nav-primary/nav-primary.module.scss
  services/web-app/components/nav-secondary/index.js
  services/web-app/components/nav-secondary/nav-secondary.js
  services/web-app/components/nav-secondary/nav-secondary.module.scss
  services/web-app/data/nav-data.js
  services/web-app/layouts/layout/layout.js
  services/web-app/layouts/layout/layout.module.scss
  services/web-app/lib/github.js
  services/web-app/pages/404.js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/library-assets/index.js
  services/web-app/pages/assets/components.js
  services/web-app/pages/assets/data-visualization.js
  services/web-app/pages/assets/elements.js
  services/web-app/pages/assets/functions.js
  services/web-app/pages/assets/index.js
  services/web-app/pages/assets/libraries.js
  services/web-app/pages/assets/patterns.js
  services/web-app/pages/assets/templates.js
  services/web-app/pages/index.js
  services/web-app/pages/standards.js
  services/web-app/types.js
Labels: status: one more review 👀

#825 fix(web-app): remove console log statement
  services/web-app/layouts/layout/layout.js
Labels: status: one more review 👀

#823 fix(web-app): remove auth for v1
  services/web-app/components/page-not-found/page-not-found.js
  services/web-app/pages/_app.js
  services/web-app/pages/_middleware.js
Labels: status: one more review 👀

#829 Deploy new services versions to prod
  service-config.prod.json
Labels: status: one more review 👀

#820 feat(web-app): add library nav data to side nav
  packages/schemas/carbon-resources.schema.json
  packages/schemas/internal/validation/library-validation.schema.json
  services/web-app/components/nav-tree/nav-tree.js
  services/web-app/data/libraries.js
  services/web-app/lib/github.js
  services/web-app/utils/tree.js
Labels: status: ready for review 👀

#796 fix(web-app): allow deep nesting in tree nav (styling)
  services/web-app/components/nav-tree/nav-tree.js
  services/web-app/components/nav-tree/nav-tree.module.scss
Labels: status: one more review 👀

#843 feat(web-app): add back to top button
  services/web-app/components/back-to-top/back-to-top.js
  services/web-app/components/back-to-top/back-to-top.module.scss
  services/web-app/components/back-to-top/index.js
  services/web-app/layouts/layout/layout.js
  services/web-app/stories/components/back-top-top.stories.js
Labels: status: ready to merge 🎉

#836 fix(web-app): left nav margin bug
  package-lock.json
  services/web-app/components/nav-tree/nav-tree.js
  services/web-app/components/nav-tree/nav-tree.module.scss
Labels: status: ready to merge 🎉

#851 feat: remove date from footer
  services/web-app/components/footer/footer.js
Labels: status: one more review 👀

#857 fix(web-app): top margin library detail page
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.module.scss
Labels: status: ready to merge 🎉

#844 feat(web-app): library details, add resources section
  packages/icons/src/main/svg/32-library.svg
  packages/icons/src/main/svg/32-npm.svg
  packages/icons/src/main/svg/npm.svg
  services/web-app/components/mdx-icon/mdx-icon.js
  services/web-app/lib/github.js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/index.module.scss
Labels: status: one more review 👀

#893 fix(web-app): asset detail page tab bottom border width
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].module.scss
Labels: status: ready to merge 🎉

#876 refactor(web-app): separate useQueryState into two hooks
  services/web-app/components/catalog/catalog.js
  services/web-app/utils/use-local-state.js
  services/web-app/utils/use-query-state.js
Labels: status: one more review 👀

#872 feat(web-app): add divider component
  package-lock.json
  services/web-app/components/divider/divider.js
  services/web-app/components/divider/divider.module.scss
  services/web-app/components/divider/index.js
  services/web-app/components/mdx/components.js
  services/web-app/pages/about-carbon/how-carbon-works.mdx
  services/web-app/pages/about-carbon/how-carbon-works.module.scss
  services/web-app/pages/about-carbon/meetups.mdx
  services/web-app/pages/about-carbon/meetups.module.scss
  services/web-app/pages/about-carbon/platform-roadmap.js
  services/web-app/pages/about-carbon/platform-roadmap.module.scss
  services/web-app/pages/mdx/divider.mdx
  services/web-app/public/mdx/events_design_playback.png
  services/web-app/public/mdx/roadmap-v0.1.png
  services/web-app/stories/mdx/divider.stories.js
Labels: status: ready to merge 🎉

#902 docs: add create/update app script to docker docs
  docs/docker.md
Labels: status: one more review 👀

#923 fix(web-app): add comma delineation for library asset list tags
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/library-assets/index.js
Labels: status: one more review 👀

#925 fix(web-app): minor styling bugs
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/[asset].js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/library-assets/index.js
  services/web-app/pages/assets/[host]/[org]/[repo]/[library]/[ref]/library-assets/index.module.scss
Labels: status: one more review 👀

#926 fix(web-app): mobile nav spacing
  services/web-app/components/nav-primary/nav-primary.js
  services/web-app/layouts/layout/layout.js
Labels: status: one more review 👀, status: ready to merge 🎉

#927 feat(web-app): add dataviz pages
  services/web-app/components/aside/aside.js
  services/web-app/components/aside/aside.module.scss
  services/web-app/data/nav-data.js
  services/web-app/pages/data-visualization/axes-and-labels.js
  services/web-app/pages/data-visualization/chart-anatomy.mdx
  services/web-app/pages/data-visualization/color-palettes.mdx
  services/web-app/pages/data-visualization/dashboards.js
  services/web-app/pages/data-visualization/get-started.js
  services/web-app/pages/data-visualization/legends.js
  services/web-app/public/data-visualization/chart-anatomy/chart-anatomy-1.png
  services/web-app/public/data-visualization/chart-anatomy/chart-anatomy-1sm.png
  services/web-app/public/data-visualization/chart-anatomy/chart-anatomy-2.png
  services/web-app/public/data-visualization/chart-anatomy/chart-anatomy-2sm.png
  services/web-app/public/data-visualization/color-palettes/alts-dark-1.png
  services/web-app/public/data-visualization/color-palettes/alts-dark-1sm.png
  services/web-app/public/data-visualization/color-palettes/alts-dark-2.png
  services/web-app/public/data-visualization/color-palettes/alts-dark-2sm.png
  services/web-app/public/data-visualization/color-palettes/alts-dark-3.png
  services/web-app/public/data-visualization/color-palettes/alts-dark-3sm.png
  services/web-app/public/data-visualization/color-palettes/alts-dark-4.png
  services/web-app/public/data-visualization/color-palettes/alts-dark-4sm.png
  services/web-app/public/data-visualization/color-palettes/alts-dark-5.png
  services/web-app/public/data-visualization/color-palettes/alts-dark-5sm.png
  services/web-app/public/data-visualization/color-palettes/alts-light-1.png
  services/web-app/public/data-visualization/color-palettes/alts-light-1sm.png
  services/web-app/public/data-visualization/color-palettes/alts-light-2.png
  services/web-app/public/data-visualization/color-palettes/alts-light-2sm.png
  services/web-app/public/data-visualization/color-palettes/alts-light-3.png
  services/web-app/public/data-visualization/color-palettes/alts-light-3sm.png
  services/web-app/public/data-visualization/color-palettes/alts-light-4.png
  services/web-app/public/data-visualization/color-palettes/alts-light-4sm.png
  services/web-app/public/data-visualization/color-palettes/alts-light-5.png
  services/web-app/public/data-visualization/color-palettes/alts-light-5sm.png
  services/web-app/public/data-visualization/color-palettes/color_gallery_1.png
  services/web-app/public/data-visualization/color-palettes/color_gallery_2.png
  services/web-app/public/data-visualization/color-palettes/color_gallery_3.png
  services/web-app/public/data-visualization/color-palettes/color_gallery_4.png
  services/web-app/public/data-visualization/color-palettes/color_gallery_5.png
  services/web-app/public/data-visualization/color-palettes/color_gallery_6.png
  services/web-app/public/data-visualization/color-palettes/color_gallery_7.png
  services/web-app/public/data-visualization/color-palettes/gradient.png
  services/web-app/public/data-visualization/color-palettes/palettes-14cat.png
  services/web-app/public/data-visualization/color-palettes/palettes-14catsm.png
  services/web-app/public/data-visualization/color-palettes/palettes-alert-sm.png
  services/web-app/public/data-visualization/color-palettes/palettes-alert.png
  services/web-app/public/data-visualization/color-palettes/palettes-div1.png
  services/web-app/public/data-visualization/color-palettes/palettes-div1sm.png
  services/web-app/public/data-visualization/color-palettes/palettes-div2.png
  services/web-app/public/data-visualization/color-palettes/palettes-div2sm.png
  services/web-app/public/data-visualization/color-palettes/palettes-mono-1.png
  services/web-app/public/data-visualization/color-palettes/palettes-mono-1sm.png
  services/web-app/public/data-visualization/color-palettes/palettes-mono-2.png
  services/web-app/public/data-visualization/color-palettes/palettes-mono-2sm.png
Labels: status: one more review 👀
