Repository carbon-design-system/carbon-platform, pull requests merged in 2022-07, with the labels that each got.

#932 feat(web-app): url strategy redefinition
  services/web-app/components/asset-catalog-item/asset-catalog-item.js
  services/web-app/components/hero/hero.module.scss
  services/web-app/components/nav-secondary/nav-secondary.js
  services/web-app/data/nav-data.js
  services/web-app/data/type.js
  services/web-app/layouts/layout/layout.js
  services/web-app/lib/github.js
  services/web-app/next.config.mjs
  services/web-app/pages/about-carbon/how-carbon-works.mdx
  services/web-app/pages/assets/index.js
  services/web-app/pages/catalogs/components.js
  services/web-app/pages/catalogs/elements.js
  services/web-app/pages/catalogs/functions.js
  services/web-app/pages/catalogs/patterns.js
  services/web-app/pages/catalogs/templates.js
  services/web-app/pages/collections/data-visualization/axes-and-labels.js
  services/web-app/pages/collections/data-visualization/chart-anatomy.mdx
  services/web-app/pages/collections/data-visualization/color-palettes.mdx
  services/web-app/pages/collections/data-visualization/dashboards.js
  services/web-app/pages/collections/data-visualization/get-started.js
  services/web-app/pages/collections/data-visualization/index.js
  services/web-app/pages/collections/data-visualization/legends.js
  services/web-app/pages/developing/index.mdx
  services/web-app/pages/elements/2x-grid/implementation.mdx
  services/web-app/pages/elements/accessibility/overview.mdx
  services/web-app/pages/elements/color/overview.mdx
  services/web-app/pages/elements/icons/contribute.mdx
  services/web-app/pages/elements/pictograms/contribute.mdx
  services/web-app/pages/elements/themes/overview.mdx
  services/web-app/pages/faq/index.mdx
  services/web-app/pages/index.js
  services/web-app/pages/index/images/assets-hero.png
  services/web-app/pages/index/images/assets-hero_mobile.png
  services/web-app/pages/index/images/chart-banner.png
  services/web-app/pages/index/images/react-banner.png
  services/web-app/pages/index/index.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.module.scss
  services/web-app/pages/libraries/index.js
  services/web-app/pages/libraries/index.module.scss
  services/web-app/stories/pages/homepage.stories.js
  sonar-project.properties
Labels: status: one more review 👀

#929 feat(web-app): Render lib side nav pages
  services/web-app/components/mdx-wrapper/mdx-wrapper.js
  services/web-app/components/remote-mdx-loader/remote-mdx-loader.js
  services/web-app/lib/github.js
  services/web-app/next.config.mjs
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/pages/[...page].js
  services/web-app/public/data/diskstore-00bb34759209d993906fdd3558c5ca23.json
  services/web-app/public/data/diskstore-0a1a6a72f130f526e6dc763a1f4142ba.json
  services/web-app/public/data/diskstore-0a92b2eb1987b5bbad6c5b3457484c31.json
  services/web-app/public/data/diskstore-0f6cb8e49d189e991cd33dd0a66f6257.json
  services/web-app/public/data/diskstore-14f3d1aeaa60bb96861fef20e2198d2e.json
  services/web-app/public/data/diskstore-1622b5cc4e99f17bf60661fde8f42779.json
  services/web-app/public/data/diskstore-1fb1fa96b5875dec84643208a446f379.json
  services/web-app/public/data/diskstore-21dcafa8613959b0fa9ff8d753680a27.json
  services/web-app/public/data/diskstore-2618e24c8de6557b920f54b430b7d777.json
  services/web-app/public/data/diskstore-306b8f9c2d86400903daaca0d7cf66a4.json
  services/web-app/public/data/diskstore-369c595c5bcd22b7ab06a6c081089237.json
  services/web-app/public/data/diskstore-3f236852d7ca89c62932512099000ac8.json
  services/web-app/public/data/diskstore-42cd28b422e03a8b188dfa116fdf61b3.json
  services/web-app/public/data/diskstore-4be2ba65e851ed09cab075dae19765af.json
  services/web-app/public/data/diskstore-5328a467caca6ccd75064714e9adc538.json
  services/web-app/public/data/diskstore-54a6946229365dceba1edb85c0d75653.json
  services/web-app/public/data/diskstore-5595d0064b46bc69310ebc8bf88d40f3.json
  services/web-app/public/data/diskstore-572578a2282fbc506d520b10793eb2f9.json
  services/web-app/public/data/diskstore-5d9b6cc02de8b7f613ce3c41899a85b6.json
  services/web-app/public/data/diskstore-5d9eacfe377d59c3c07ac435f558a4ce.json
  services/web-app/public/data/diskstore-61ccb046e1f2a88ca13b539fa3c65734.json
  services/web-app/public/data/diskstore-61fe53d6607740d1fce4ba9335ea1d5a.json
  services/web-app/public/data/diskstore-6474682a7aa9d0190bee318590eb67c0.json
  services/web-app/public/data/diskstore-651deefe7616efd27a78f23957e45237.json
  services/web-app/public/data/diskstore-6700a8138e474921df3bc45e9c7e3af1.json
  services/web-app/public/data/diskstore-6b8e31e57d0c3e6261c537f820348230.json
  services/web-app/public/data/diskstore-6f42b309fc47965c740024a09ef5d572.json
  services/web-app/public/data/diskstore-6f944ce5123e9c75e2dba9c773922d12.json
  services/web-app/public/data/diskstore-7aafb6a0e1f2636030724f6ef39eb9d8.json
  services/web-app/public/data/diskstore-80a26e9923018115c09f08fa537a5ece.json
  services/web-app/public/data/diskstore-85945c4a4586f9f5d725647a2ea49894.json
  services/web-app/public/data/diskstore-85fb9cc60d29c16cc69414ce347f9807.json
  services/web-app/public/data/diskstore-8e8d2f4e72b62700495cdb1473c24a3c.json
  services/web-app/public/data/diskstore-9093e83b1dd1f8268ca8a859a945db67.json
  services/web-app/public/data/diskstore-9196fcde9cca3fad47159511b5349ad4.json
  services/web-app/public/data/diskstore-9a18ccd03fa539649f3e7b5a31a814ad.json
  services/web-app/public/data/diskstore-9ae3b2e6740152c155ec6ca6a8e13da3.json
  services/web-app/public/data/diskstore-9beeb44101f5021fda37923a9eebe85e.json
  services/web-app/public/data/diskstore-a1783be611d336a33c231428727ed4f4.json
  services/web-app/public/data/diskstore-a4b2ee3d50b203d23431f6d8f9f11b2d.json
  services/web-app/public/data/diskstore-a5fecebfdb24859f990bfad1df297a40.json
  services/web-app/public/data/diskstore-a6413e28184faa1a2377ccbf2193998f.json
  services/web-app/public/data/diskstore-b08bc5ae84c410bdcc9e8cc34d2fb64f.json
  services/web-app/public/data/diskstore-b100b8c9ff3e700ad44dddd81b151750.json
  services/web-app/public/data/diskstore-b14f8d26ea658e9529d76906948473c9.json
  services/web-app/public/data/diskstore-b3c47c08f10a4c487b0923312ddcad95.json
  services/web-app/public/data/diskstore-ba32c7ef1db60312c27bd5fb0ce868b9.json
  services/web-app/public/data/diskstore-c60d531f19c9be1b7f72ca5f367d787c.json
  services/web-app/public/data/diskstore-ca669080704a6a56594913634bf871bb.json
  services/web-app/public/data/diskstore-de013d5cf0b883eaeaaf20665a1de10c.json
  services/web-app/public/data/diskstore-e7225b07dfba68f3d54e50e3fa6d4489.json
  services/web-app/public/data/diskstore-ea9312322798350eaf7a3a5d029087a8.json
  services/web-app/public/data/diskstore-ee93f7862d2175789208d74dc776a7fb.json
  services/web-app/public/data/diskstore-f88fbf8c7486a268df51a58ebff2c582.json
  services/web-app/utils/string.js
Labels: status: one more review 👀

#976 docs: update rabbitmq guidance to use version 3.9
  docs/docker.md
  docs/messaging.md
Labels: status: one more review 👀

#984 feat(web-app): rename sponsor to maintainer
  services/web-app/components/asset-catalog-item/asset-catalog-item.js
  services/web-app/components/asset-catalog-item/asset-catalog-item.module.scss
  services/web-app/components/assets-catalog/assets-catalog.js
  services/web-app/data/filters.js
  services/web-app/data/libraries.mjs
  services/web-app/data/teams.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/index.module.scss
  services/web-app/pages/libraries/index.js
  services/web-app/pages/libraries/index.module.scss
  services/web-app/typedefs.js
  services/web-app/types.js
Labels: status: one more review 👀

#928 feat: index cloud cognitive
  services/web-app/data/libraries.mjs
  services/web-app/public/assets/thumbnails/about-modal.svg
  services/web-app/public/assets/thumbnails/action-bar.svg
  services/web-app/public/assets/thumbnails/action-set.svg
  services/web-app/public/assets/thumbnails/api-key-modal.svg
  services/web-app/public/assets/thumbnails/breadcrumb-with-overflow.svg
  services/web-app/public/assets/thumbnails/button-menu.svg
  services/web-app/public/assets/thumbnails/button-set-with-overflow.svg
  services/web-app/public/assets/thumbnails/cascade.svg
  services/web-app/public/assets/thumbnails/combo-button.svg
  services/web-app/public/assets/thumbnails/create-full-page.svg
  services/web-app/public/assets/thumbnails/create-modal.svg
  services/web-app/public/assets/thumbnails/create-tearsheet-narrow.svg
  services/web-app/public/assets/thumbnails/create-tearsheet.svg
  services/web-app/public/assets/thumbnails/data-grid.svg
  services/web-app/public/assets/thumbnails/data-spreadsheet.svg
  services/web-app/public/assets/thumbnails/edit-side-panel.svg
  services/web-app/public/assets/thumbnails/empty-state.svg
  services/web-app/public/assets/thumbnails/export-modal.svg
  services/web-app/public/assets/thumbnails/expressive-card.svg
  services/web-app/public/assets/thumbnails/http-error.svg
  services/web-app/public/assets/thumbnails/import-modal.svg
  services/web-app/public/assets/thumbnails/inline-edit.svg
  services/web-app/public/assets/thumbnails/modified-tabs.svg
  services/web-app/public/assets/thumbnails/multi-add-select.svg
  services/web-app/public/assets/thumbnails/notifications-panel.svg
  services/web-app/public/assets/thumbnails/options-tile.svg
  services/web-app/public/assets/thumbnails/productive-card.svg
  services/web-app/public/assets/thumbnails/remove-modal.svg
  services/web-app/public/assets/thumbnails/saving.svg
  services/web-app/public/assets/thumbnails/side-panel.svg
  services/web-app/public/assets/thumbnails/single-add-select.svg
  services/web-app/public/assets/thumbnails/status-icon.svg
  services/web-app/public/assets/thumbnails/tag-set.svg
  services/web-app/public/assets/thumbnails/tear-sheet.svg
  services/web-app/public/assets/thumbnails/tearsheet.svg
  services/web-app/public/assets/thumbnails/user-profile-image.svg
  services/web-app/public/assets/thumbnails/web-terminal.svg
  services/web-app/public/data/diskstore-0001677b733580022d08107aafebe7c3.json
  services/web-app/public/data/diskstore-921af6022344f1e7ae4a36b5efc6c24d.json
  services/web-app/public/data/diskstore-ba9d56e508cb72b7163d49ab29277952.json
  services/web-app/public/data/diskstore-d4798bc8c96fe55de9b840fe8a781521.json
Labels: status: ready to merge 🎉

#983 fix(web-app): create drop shadow variable for consistent shadows
  services/web-app/components/catalog-sort/catalog-sort.module.scss
  services/web-app/components/color-token-table/color-token-table.module.scss
  services/web-app/components/svg-libraries/svg-library.module.scss
  services/web-app/components/typeset-style/typeset-style.module.scss
  services/web-app/styles/_variables.scss
Labels: status: ready to merge 🎉

#985 fix(web-app): reduce z-index for svg libraries
  services/web-app/components/back-to-top/back-to-top.module.scss
  services/web-app/components/page-tabs/page-tabs.module.scss
  services/web-app/components/svg-libraries/svg-library.module.scss
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/[asset]/index.module.scss
  services/web-app/styles/_variables.scss
  services/web-app/styles/vendor/_overrides.scss
Labels: status: ready to merge 🎉

#957 fix(web-app): set correct classname for pictogram grid
  services/web-app/components/svg-libraries/pictogram-library/pictogram-category.js
Labels: status: one more review 👀

#1014 feat(mdx-sanitizer): add mdx test files
  .commitlintrc.js
  packages/api/src/test/mdx-sanitizer/test-files/export.mdx
  packages/api/src/test/mdx-sanitizer/test-files/format-error.mdx
  packages/api/src/test/mdx-sanitizer/test-files/html-comments.mdx
  packages/api/src/test/mdx-sanitizer/test-files/import.mdx
  packages/api/src/test/mdx-sanitizer/test-files/inline-style.mdx
  packages/api/src/test/mdx-sanitizer/test-files/no-errors.mdx
  packages/api/src/test/mdx-sanitizer/test-files/script.mdx
  packages/api/src/test/mdx-sanitizer/test-files/unknown-component.mdx
Labels: status: ready to merge 🎉

#1029 fix: udpates to how carbon works
  services/web-app/pages/about-carbon/how-carbon-works.mdx
  services/web-app/public/about-carbon/ecosystem.png
Labels: status: one more review 👀

#1031 fix(web-app): proxy server conversion to esm
  services/web-app/esbuild.mjs
  services/web-app/package.json
  services/web-app/proxy-server.mjs
Labels: status: one more review 👀

#1034 ci: add workflow to auto-comment on prs
  .github/workflows/pr-bot-commenter.yml
  package-lock.json
  packages/micromanage/package.json
  packages/micromanage/scripts/add-pr-comment.mjs
Labels: status: merge conflict 🚫

#1026 docs: move resource schema to website page
  services/web-app/data/nav-data.js
  services/web-app/pages/contribute/documentation.mdx
  services/web-app/pages/contributing/add-ons.mdx
  services/web-app/pages/contributing/bugs-and-requests.js
  services/web-app/pages/contributing/components.js
  services/web-app/pages/contributing/icons.js
  services/web-app/pages/contributing/overview.js
  services/web-app/pages/contributing/patterns.js
  services/web-app/pages/contributing/pictograms.js
  services/web-app/pages/contributing/schema.mdx
  services/web-app/pages/designing/sketch.mdx
  services/web-app/pages/faq/index.mdx
Labels: status: one more review 👀

#1033 fix(web-app): display design only tag in library assets
  services/web-app/data/type.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js
Labels: status: ready to merge 🎉

#1020 feat(web-app): Resolve design kit schema references
  package-lock.json
  packages/schemas/internal/validation/design-kit-validation.schema.json
  packages/schemas/internal/validation/library-validation.schema.json
  services/web-app/data/design-kits.js
  services/web-app/lib/github.js
  services/web-app/package.json
  services/web-app/typedefs.js
  services/web-app/utils/resources.js
Labels: status: one more review 👀

#1061 fix(web-app): handle relative urls in library pages
  services/web-app/data/libraries.mjs
  services/web-app/lib/github.js
  services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/pages/[...page].js
Labels: status: ready to merge 🎉

#1081 fix(web-app): storybook compile error
  services/web-app/components/asset-catalog-item/asset-catalog-item.module.scss
  services/web-app/components/back-to-top/back-to-top.module.scss
  services/web-app/components/catalog-sort/catalog-sort.module.scss
  services/web-app/components/color-token-table/color-token-table.module.scss
  services/web-app/components/library-catalog-item/library-catalog-item.module.scss
  services/web-app/components/page-breadcrumb/page-breadcrumb.module.scss
  services/web-app/components/page-header/page-header.module.scss
  services/web-app/components/page-nav/page-nav.module.scss
  services/web-app/components/page-tabs/page-tabs.module.scss
  services/web-app/components/resource-card/resource-card.module.scss
  services/web-app/components/svg-libraries/svg-library.module.scss
  services/web-app/components/typeset-style/typeset-style.module.scss
  services/web-app/styles/vendor/_overrides.scss
Labels: status: ready to merge 🎉
